# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
[
  {id: 1,email: 'admin@gmail.com', password: '123456', password_confirmation: '123456'},
  {id: 2,email: 'teacher@gmail.com', password: '123456', password_confirmation: '123456'},
  {id: 3,email: 'teacher1@gmail.com', password: '123456', password_confirmation: '123456'},
  {id: 4,email: 'loc@gmail.com', password: '123456', password_confirmation: '123456'},
  {id: 5,email: 'linh@gmail.com', password: '123456', password_confirmation: '123456'},
].each do |attr|
  user = User.find_by(id: attr[:id])
  User.transaction do
    unless user
      user = User.new(attr)
      user.save
    else
      user.update_attributes attr
    end
  end
end

[
{id: 1, code:'01', name: "Thành phố Hà Nội", kind: "Thành phố Trung ương"},
{id: 2, code:'02', name: 'Tỉnh Hà Giang', kind: 'Tỉnh'},
{id: 3, code:'04', name: 'Tỉnh Cao Bằng', kind: 'Tỉnh'},
{id: 4, code:'06', name: 'Tỉnh Bắc Kạn', kind: 'Tỉnh'},
{id: 5, code:'08', name: 'Tỉnh Tuyên Quang', kind: 'Tỉnh'},
{id: 6, code:'10', name: 'Tỉnh Lào Cai', kind: 'Tỉnh'},
{id: 7, code:'11', name: 'Tỉnh Điện Biên', kind: 'Tỉnh'},
{id: 8, code:'12', name: 'Tỉnh Lai Châu', kind: 'Tỉnh'},
{id: 9, code:'14', name: 'Tỉnh Sơn La', kind: 'Tỉnh'},
{id: 10, code:'15', name: 'Tỉnh Yên Bái', kind: 'Tỉnh'},
{id: 11, code:'17', name: 'Tỉnh Hoà Bình', kind: 'Tỉnh'},
{id: 12, code:'19', name: 'Tỉnh Thái Nguyên', kind: 'Tỉnh'},
{id: 13, code:'20', name: 'Tỉnh Lạng Sơn', kind: 'Tỉnh'},
{id: 14, code:'22', name: 'Tỉnh Quảng Ninh', kind: 'Tỉnh'},
{id: 15, code:'24', name: 'Tỉnh Bắc Giang', kind: 'Tỉnh'},
{id: 16, code:'25', name: 'Tỉnh Phú Thọ', kind: 'Tỉnh'},
{id: 17, code:'26', name: 'Tỉnh Vĩnh Phúc', kind: 'Tỉnh'},
{id: 18, code:'27', name: 'Tỉnh Bắc Ninh', kind: 'Tỉnh'},
{id: 19, code:'30', name: 'Tỉnh Hải Dương', kind: 'Tỉnh'},
{id: 20, code:'31', name: 'Thành phố Hải Phòng',  kind:'Thành phố Trung ương'},
{id: 21, code:'33', name: 'Tỉnh Hưng Yên', kind: 'Tỉnh'},
{id: 22, code:'34', name: 'Tỉnh Thái Bình', kind: 'Tỉnh'},
{id: 23, code:'35', name: 'Tỉnh Hà Nam', kind: 'Tỉnh'},
{id: 24, code:'36', name: 'Tỉnh Nam Định', kind: 'Tỉnh'},
{id: 25, code:'37', name: 'Tỉnh Ninh Bình', kind: 'Tỉnh'},
{id: 26, code:'38', name: 'Tỉnh Thanh Hóa', kind: 'Tỉnh'},
{id: 27, code:'40', name: 'Tỉnh Nghệ An', kind: 'Tỉnh'},
{id: 28, code:'42', name: 'Tỉnh Hà Tĩnh', kind: 'Tỉnh'},
{id: 29, code:'44', name: 'Tỉnh Quảng Bình', kind: 'Tỉnh'},
{id: 30, code:'45', name: 'Tỉnh Quảng Trị', kind: 'Tỉnh'},
{id: 31, code:'46', name: 'Tỉnh Thừa Thiên Huế', kind: 'Tỉnh'},
{id: 32, code:'48', name: 'Thành phố Đà Nẵng',  kind:'Thành phố Trung ương'},
{id: 33, code:'49', name: 'Tỉnh Quảng Nam', kind: 'Tỉnh'},
{id: 34, code:'51', name: 'Tỉnh Quảng Ngãi', kind: 'Tỉnh'},
{id: 35, code:'52', name: 'Tỉnh Bình Định', kind: 'Tỉnh'},
{id: 36, code:'54', name: 'Tỉnh Phú Yên', kind: 'Tỉnh'},
{id: 37, code:'56', name: 'Tỉnh Khánh Hòa', kind: 'Tỉnh'},
{id: 38, code:'58', name: 'Tỉnh Ninh Thuận', kind: 'Tỉnh'},
{id: 39, code:'60', name: 'Tỉnh Bình Thuận', kind: 'Tỉnh'},
{id: 40, code:'62', name: 'Tỉnh Kon Tum', kind: 'Tỉnh'},
{id: 41, code:'64', name: 'Tỉnh Gia Lai', kind: 'Tỉnh'},
{id: 42, code:'66', name: 'Tỉnh Đắk Lắk', kind: 'Tỉnh'},
{id: 43, code:'67', name: 'Tỉnh Đắk Nông', kind: 'Tỉnh'},
{id: 44, code:'68', name: 'Tỉnh Lâm Đồng', kind: 'Tỉnh'},
{id: 45, code:'70', name: 'Tỉnh Bình Phước', kind: 'Tỉnh'},
{id: 46, code:'72', name: 'Tỉnh Tây Ninh', kind: 'Tỉnh'},
{id: 47, code:'74', name: 'Tỉnh Bình Dương', kind: 'Tỉnh'},
{id: 48, code:'75', name: 'Tỉnh Đồng Nai', kind: 'Tỉnh'},
{id: 49, code:'77', name: 'Tỉnh Bà Rịa - Vũng Tàu', kind: 'Tỉnh'},
{id: 50, code:'79', name: 'Thành phố Hồ Chí Minh',  kind:'Thành phố Trung ương'},
{id: 51, code:'80', name: 'Tỉnh Long An', kind: 'Tỉnh'},
{id: 52, code:'82', name: 'Tỉnh Tiền Giang', kind: 'Tỉnh'},
{id: 53, code:'83', name: 'Tỉnh Bến Tre', kind: 'Tỉnh'},
{id: 54, code:'84', name: 'Tỉnh Trà Vinh', kind: 'Tỉnh'},
{id: 55, code:'86', name: 'Tỉnh Vĩnh Long', kind: 'Tỉnh'},
{id: 56, code:'87', name: 'Tỉnh Đồng Tháp', kind: 'Tỉnh'},
{id: 57, code:'89', name: 'Tỉnh An Giang', kind: 'Tỉnh'},
{id: 58, code:'91', name: 'Tỉnh Kiên Giang', kind: 'Tỉnh'},
{id: 59, code:'92', name: 'Thành phố Cần Thơ',  kind:'Thành phố Trung ương'},
{id: 60, code:'93', name: 'Tỉnh Hậu Giang', kind: 'Tỉnh'},
{id: 61, code:'94', name: 'Tỉnh Sóc Trăng', kind: 'Tỉnh'},
{id: 62, code:'95', name: 'Tỉnh Bạc Liêu', kind: 'Tỉnh'},
{id: 63, code:'96', name: 'Tỉnh Cà Mau', kind: 'Tỉnh'},
].each do |attr|
  city = City.find_by(id: attr[:id])
  City.transaction do
    unless city
      city = City.new(attr)
      city.save
    else
      city.update_attributes attr
    end
  end
end
# // Distric
[
  {id: 1, code: '001', name: 'Quận Ba Đình', kind: 'Quận', city_id: 1},
  {id: 2, code: '002', name: 'Quận Hoàn Kiếm', kind: 'Quận', city_id: 1},
  {id: 3, code: '003', name: 'Quận Tây Hồ', kind: 'Quận', city_id: 1},
  {id: 4, code: '004', name: 'Quận Long Biên', kind: 'Quận', city_id: 1},
  {id: 5, code: '005', name: 'Quận Cầu Giấy', kind: 'Quận', city_id: 1},
  {id: 6, code: '006', name: 'Quận Đống Đa', kind: 'Quận', city_id: 1},
  {id: 7, code: '007', name: 'Quận Hai Bà Trưng', kind: 'Quận', city_id: 1},
  {id: 8, code: '008', name: 'Quận Hoàng Mai', kind: 'Quận', city_id: 1},
  {id: 9, code: '009', name: 'Quận Thanh Xuân', kind: 'Quận', city_id: 1},
  {id: 10, code: '016', name: 'Huyện Sóc Sơn', kind: 'Huyện', city_id: 1},
  {id: 11, code: '017', name: 'Huyện Đông Anh', kind: 'Huyện', city_id: 1},
  {id: 12, code: '018', name: 'Huyện Gia Lâm', kind: 'Huyện', city_id: 1},
  {id: 13, code: '019', name: 'Quận Nam Từ Liêm', kind: 'Quận', city_id: 1},
  {id: 14, code: '020', name: 'Huyện Thanh Trì', kind: 'Huyện', city_id: 1},
  {id: 15, code: '021', name: 'Quận Bắc Từ Liêm', kind: 'Quận', city_id: 1},
  {id: 16, code: '024', name: 'Thành phố Hà Giang', kind: 'Thành phố', city_id: 2},
  {id: 17, code: '026', name: 'Huyện Đồng Văn', kind: 'Huyện', city_id: 2},
  {id: 18, code: '027', name: 'Huyện Mèo Vạc', kind: 'Huyện', city_id: 2},
  {id: 19, code: '028', name: 'Huyện Yên Minh', kind: 'Huyện', city_id: 2},
  {id: 20, code: '029', name: 'Huyện Quản Bạ', kind: 'Huyện', city_id: 2},
  {id: 21, code: '030', name: 'Huyện Vị Xuyên', kind: 'Huyện', city_id: 2},
  {id: 22, code: '031', name: 'Huyện Bắc Mê', kind: 'Huyện', city_id: 2},
  {id: 23, code: '032', name: 'Huyện Hoàng Su Phì', kind: 'Huyện', city_id: 2},
  {id: 24, code: '033', name: 'Huyện Xín Mần', kind: 'Huyện', city_id: 2},
  {id: 25, code: '034', name: 'Huyện Bắc Quang', kind: 'Huyện', city_id: 2},
  {id: 26, code: '035', name: 'Huyện Quang Bình', kind: 'Huyện', city_id: 2},
  {id: 27, code: '040', name: 'Thành phố Cao Bằng', kind: 'Thành phố', city_id: 3},
  {id: 28, code: '042', name: 'Huyện Bảo Lâm', kind: 'Huyện', city_id: 3},
  {id: 29, code: '043', name: 'Huyện Bảo Lạc', kind: 'Huyện', city_id: 3},
  {id: 30, code: '044', name: 'Huyện Thông Nông', kind: 'Huyện', city_id: 3},
  {id: 31, code: '045', name: 'Huyện Hà Quảng', kind: 'Huyện', city_id: 3},
  {id: 32, code: '046', name: 'Huyện Trà Lĩnh', kind: 'Huyện', city_id: 3},
  {id: 33, code: '047', name: 'Huyện Trùng Khánh', kind: 'Huyện', city_id: 3},
  {id: 34, code: '048', name: 'Huyện Hạ Lang', kind: 'Huyện', city_id: 3},
  {id: 35, code: '049', name: 'Huyện Quảng Uyên', kind: 'Huyện', city_id: 3},
  {id: 36, code: '050', name: 'Huyện Phục Hoà', kind: 'Huyện', city_id: 3},
  {id: 37, code: '051', name: 'Huyện Hoà An', kind: 'Huyện', city_id: 3},
  {id: 38, code: '052', name: 'Huyện Nguyên Bình', kind: 'Huyện', city_id: 3},
  {id: 39, code: '053', name: 'Huyện Thạch An', kind: 'Huyện', city_id: 3},
  {id: 40, code: '058', name: 'Thành Phố Bắc Kạn', kind: 'Thành phố', city_id: 4},
  {id: 41, code: '060', name: 'Huyện Pác Nặm', kind: 'Huyện', city_id: 4},
  {id: 42, code: '061', name: 'Huyện Ba Bể', kind: 'Huyện', city_id: 4},
  {id: 43, code: '062', name: 'Huyện Ngân Sơn', kind: 'Huyện', city_id: 4},
  {id: 44, code: '063', name: 'Huyện Bạch Thông', kind: 'Huyện', city_id: 4},
  {id: 45, code: '064', name: 'Huyện Chợ Đồn', kind: 'Huyện', city_id: 4},
  {id: 46, code: '065', name: 'Huyện Chợ Mới', kind: 'Huyện', city_id: 4},
  {id: 47, code: '066', name: 'Huyện Na Rì', kind: 'Huyện', city_id: 4},
  {id: 48, code: '070',name: 'Thành phố Tuyên Quang', kind: 'Thành phố', city_id: 5},
  {id: 49, code: '071',name: 'Huyện Lâm Bình', kind: 'Huyện', city_id: 5},
  {id: 50, code: '072',name: 'Huyện Nà Hang', kind: 'Huyện', city_id: 5},
  {id: 51, code: '073',name: 'Huyện Chiêm Hóa', kind: 'Huyện', city_id: 5},
  {id: 52, code: '074',name: 'Huyện Hàm Yên', kind: 'Huyện', city_id: 5},
  {id: 53, code: '075',name: 'Huyện Yên Sơn', kind: 'Huyện', city_id: 5},
  {id: 54, code: '076',name: 'Huyện Sơn Dương', kind: 'Huyện', city_id: 5},
  {id: 55, code: '080',name: 'Thành phố Lào Cai', kind: 'Thành phố', city_id: 6},
  {id: 56, code: '082',name: 'Huyện Bát Xát', kind: 'Huyện', city_id: 6},
  {id: 57, code: '083',name: 'Huyện Mường Khương', kind: 'Huyện', city_id: 6},
  {id: 58, code: '084',name: 'Huyện Si Ma Cai', kind: 'Huyện', city_id: 6},
  {id: 59, code: '085',name: 'Huyện Bắc Hà', kind: 'Huyện', city_id: 6},
  {id: 60, code: '086',name: 'Huyện Bảo Thắng', kind: 'Huyện', city_id: 6},
  {id: 61, code: '087',name: 'Huyện Bảo Yên', kind: 'Huyện', city_id: 6},
  {id: 62, code: '088',name: 'Huyện Sa Pa', kind: 'Huyện', city_id: 6},
  {id: 63, code: '089',name: 'Huyện Văn Bàn', kind: 'Huyện', city_id: 6},
  {id: 63, code: '094',name: 'Thành phố Điện Biên Phủ', kind: 'Thành phố', city_id: 7},
  {id: 65, code: '095',name: 'Thị Xã Mường Lay', kind: 'Thị xã', city_id: 7},
  {id: 66, code: '096',name: 'Huyện Mường Nhé', kind: 'Huyện', city_id: 7},
  {id: 67, code: '097',name: 'Huyện Mường Chà', kind: 'Huyện', city_id: 7},
  {id: 68, code: '098',name: 'Huyện Tủa Chùa', kind: 'Huyện', city_id: 7},
  {id: 69, code: '099',name: 'Huyện Tuần Giáo', kind: 'Huyện', city_id: 7},
  {id: 70, code: '100',name: 'Huyện Điện Biên', kind: 'Huyện', city_id: 7},
  {id: 71, code: '101',name: 'Huyện Điện Biên Đông', kind: 'Huyện', city_id: 7},
  {id: 72, code: '102',name: 'Huyện Mường Ảng', kind: 'Huyện', city_id: 7},
  {id: 73, code: '103',name: 'Huyện Nậm Pồ', kind: 'Huyện', city_id: 7},
  {id: 74, code: '105',name: 'Thành phố Lai Châu', kind: 'Thành phố', city_id: 8},
  {id: 75, code: '106',name: 'Huyện Tam Đường', kind: 'Huyện', city_id: 8},
  {id: 76, code: '107',name: 'Huyện Mường Tè', kind: 'Huyện', city_id: 8},
  {id: 77, code: '108',name: 'Huyện Sìn Hồ', kind: 'Huyện', city_id: 8},
  {id: 78, code: '109',name: 'Huyện Phong Thổ', kind: 'Huyện', city_id: 8},
  {id: 89, code: '110',name: 'Huyện Than Uyên', kind: 'Huyện', city_id: 8},
  {id: 80, code: '111',name: 'Huyện Tân Uyên', kind: 'Huyện', city_id: 8},
  {id: 81, code: '112',name: 'Huyện Nậm Nhùn', kind: 'Huyện', city_id: 8},
  {id: 82, code: '116',name: 'Thành phố Sơn La', kind: 'Thành phố', city_id: 9},
  {id: 83, code: '118',name: 'Huyện Quỳnh Nhai', kind: 'Huyện', city_id: 9},
  {id: 84, code: '119',name: 'Huyện Thuận Châu', kind: 'Huyện', city_id: 9},
  {id: 85, code: '120',name: 'Huyện Mường La', kind: 'Huyện', city_id: 9},
  {id: 86, code: '121',name: 'Huyện Bắc Yên', kind: 'Huyện', city_id: 9},
  {id: 87, code: '122',name: 'Huyện Phù Yên', kind: 'Huyện', city_id: 9},
  {id: 88, code: '123',name: 'Huyện Mộc Châu', kind: 'Huyện', city_id: 9},
  {id: 89, code: '124',name: 'Huyện Yên Châu', kind: 'Huyện', city_id: 9},
  {id: 90, code: '125',name: 'Huyện Mai Sơn', kind: 'Huyện', city_id: 9},
  {id: 91, code: '126',name: 'Huyện Sông Mã', kind: 'Huyện', city_id: 9},
  {id: 92, code: '127',name: 'Huyện Sốp Cộp', kind: 'Huyện', city_id: 9},
  {id: 93, code: '128',name: 'Huyện Vân Hồ', kind: 'Huyện', city_id: 9},
  {id: 94, code: '132',name: 'Thành phố Yên Bái', kind: 'Thành phố', city_id: 10},
  {id: 95, code: '133',name: 'Thị xã Nghĩa Lộ', kind: 'Thị xã', city_id: 10},
  {id: 96, code: '135',name: 'Huyện Lục Yên', kind: 'Huyện', city_id: 10},
  {id: 97, code: '136',name: 'Huyện Văn Yên', kind: 'Huyện', city_id: 10},
  {id: 98, code: '137',name: 'Huyện Mù Căng Chải', kind: 'Huyện', city_id: 10},
  {id: 99, code: '138',name: 'Huyện Trấn Yên', kind: 'Huyện', city_id: 10},
  {id: 100, code: '139',name: 'Huyện Trạm Tấu', kind: 'Huyện', city_id: 10},
  {id: 101, code: '140',name: 'Huyện Văn Chấn', kind: 'Huyện', city_id: 10},
  {id: 102, code: '141',name: 'Huyện Yên Bình', kind: 'Huyện', city_id: 10},
  {id: 103, code: '148', name: 'Thành phố Hòa Bình', kind: 'Thành phố', city_id: 11},
  {id: 104, code: '150', name: 'Huyện Đà Bắc', kind: 'Huyện', city_id: 11},
  {id: 105, code: '151', name: 'Huyện Kỳ Sơn', kind: 'Huyện', city_id: 11},
  {id: 106, code: '152', name: 'Huyện Lương Sơn', kind: 'Huyện', city_id: 11},
  {id: 107, code: '153', name: 'Huyện Kim Bôi', kind: 'Huyện', city_id: 11},
  {id: 108, code: '154', name: 'Huyện Cao Phong', kind: 'Huyện', city_id: 11},
  {id: 109, code: '155', name: 'Huyện Tân Lạc', kind: 'Huyện', city_id: 11},
  {id: 110, code: '156', name: 'Huyện Mai Châu', kind: 'Huyện', city_id: 11},
  {id: 111, code: '157', name: 'Huyện Lạc Sơn', kind: 'Huyện', city_id: 11},
  {id: 112, code: '158', name: 'Huyện Yên Thủy', kind: 'Huyện', city_id: 11},
  {id: 113, code: '159', name: 'Huyện Lạc Thủy', kind: 'Huyện', city_id: 11},
  {id: 114, code: '164', name: 'Thành phố Thái Nguyên', kind: 'Thành phố', city_id: 12},
  {id: 115, code: '165', name: 'Thành phố Sông Công', kind: 'Thành phố', city_id: 12},
  {id: 116, code: '167', name: 'Huyện Định Hóa',kind:  'Huyện', city_id: 12},
  {id: 117, code: '168', name: 'Huyện Phú Lương',kind:  'Huyện', city_id: 12},
  {id: 118, code: '169', name: 'Huyện Đồng Hỷ',kind:  'Huyện', city_id: 12},
  {id: 119, code: '170', name: 'Huyện Võ Nhai',kind:  'Huyện', city_id: 12},
  {id: 120, code: '171', name: 'Huyện Đại Từ',kind:  'Huyện', city_id: 12},
  {id: 121, code: '172', name: 'Thị xã Phổ Yên', kind: 'Thị xã', city_id: 12},
  {id: 122, code: '173', name: 'Huyện Phú Bình',kind: 'Huyện', city_id: 12},
  {id: 123, code: '178', name: 'Thành phố Lạng Sơn', kind: 'Thành phố', city_id: 13},
  {id: 124, code: '180', name: 'Huyện Tràng Định', kind: 'Huyện', city_id: 13},
  {id: 125, code: '181', name: 'Huyện Bình Gia', kind: 'Huyện', city_id: 13},
  {id: 126, code: '182', name: 'Huyện Văn Lãng', kind: 'Huyện', city_id: 13},
  {id: 127, code: '183', name: 'Huyện Cao Lộc', kind: 'Huyện', city_id: 13},
  {id: 128, code: '184', name: 'Huyện Văn Quan', kind: 'Huyện', city_id: 13},
  {id: 129, code: '185', name: 'Huyện Bắc Sơn', kind: 'Huyện', city_id: 13},
  {id: 130, code: '186', name: 'Huyện Hữu Lũng', kind: 'Huyện', city_id: 13},
  {id: 131, code: '187', name: 'Huyện Chi Lăng', kind: 'Huyện', city_id: 13},
  {id: 132, code: '188', name: 'Huyện Lộc Bình', kind: 'Huyện', city_id: 13},
  {id: 133, code: '189', name: 'Huyện Đình Lập', kind: 'Huyện', city_id: 13},
  {id: 134, code: '193',name: 'Thành phố Hạ Long', kind: 'Thành phố', city_id: 14},
  {id: 135, code: '194',name: 'Thành phố Móng Cái', kind: 'Thành phố', city_id: 14},
  {id: 136, code: '195',name: 'Thành phố Cẩm Phả', kind: 'Thành phố', city_id: 14},
  {id: 137, code: '196',name: 'Thành phố Uông Bí', kind: 'Thành phố', city_id: 14},
  {id: 138, code: '198',name: 'Huyện Bình Liêu', kind: 'Huyện', city_id: 14},
  {id: 139, code: '199',name: 'Huyện Tiên Yên', kind: 'Huyện', city_id: 14},
  {id: 140, code: '200',name: 'Huyện Đầm Hà', kind: 'Huyện', city_id: 14},
  {id: 141, code: '201',name: 'Huyện Hải Hà', kind: 'Huyện', city_id: 14},
  {id: 142, code: '202',name: 'Huyện Ba Chẽ', kind: 'Huyện', city_id: 14},
  {id: 143, code: '203',name: 'Huyện Vân Đồn', kind: 'Huyện', city_id: 14},
  {id: 144, code: '204',name: 'Huyện Hoành Bồ', kind: 'Huyện', city_id: 14},
  {id: 145, code: '205',name: 'Thị xã Đông Triều', kind: 'Thị xã', city_id: 14},
  {id: 146, code: '206',name: 'Thị xã Quảng Yên', kind: 'Thị xã', city_id: 14},
  {id: 147, code: '207',name: 'Huyện Cô Tô', kind: 'Huyện', city_id: 14},
  {id: 148, code: '213',name: 'Thành phố Bắc Giang', kind: 'Thành phố', city_id: 15},
  {id: 149, code: '215',name: 'Huyện Yên Thế', kind: 'Huyện', city_id: 15},
  {id: 150, code: '216',name: 'Huyện Tân Yên', kind: 'Huyện', city_id: 15},
  {id: 151, code: '217',name: 'Huyện Lạng Giang', kind: 'Huyện', city_id: 15},
  {id: 152, code: '218',name: 'Huyện Lục Nam', kind: 'Huyện', city_id: 15},
  {id: 153, code: '219',name: 'Huyện Lục Ngạn', kind: 'Huyện', city_id: 15},
  {id: 154, code: '220',name: 'Huyện Sơn Động', kind: 'Huyện', city_id: 15},
  {id: 155, code: '221',name: 'Huyện Yên Dũng', kind: 'Huyện', city_id: 15},
  {id: 156, code: '222',name: 'Huyện Việt Yên', kind: 'Huyện', city_id: 15},
  {id: 157, code: '223',name: 'Huyện Hiệp Hòa', kind: 'Huyện', city_id: 15},
  {id: 158, code: '227',name: 'Thành phố Việt Trì', kind: 'Thành phố', city_id: 16},
  {id: 159, code: '228',name: 'Thị xã Phú Thọ', kind: 'Thị xã', city_id: 16},
  {id: 160, code: '230',name: 'Huyện Đoan Hùng', kind: 'Huyện', city_id: 16},
  {id: 161, code: '231',name: 'Huyện Hạ Hoà', kind: 'Huyện', city_id: 16},
  {id: 162, code: '232',name: 'Huyện Thanh Ba', kind: 'Huyện', city_id: 16},
  {id: 163, code: '233',name: 'Huyện Phù Ninh', kind: 'Huyện', city_id: 16},
  {id: 164, code: '234',name: 'Huyện Yên Lập', kind: 'Huyện', city_id: 16},
  {id: 165, code: '235',name: 'Huyện Cẩm Khê', kind: 'Huyện', city_id: 16},
  {id: 166, code: '236',name: 'Huyện Tam Nông', kind: 'Huyện', city_id: 16},
  {id: 167, code: '237',name: 'Huyện Lâm Thao', kind: 'Huyện', city_id: 16},
  {id: 168, code: '238',name: 'Huyện Thanh Sơn', kind: 'Huyện', city_id: 16},
  {id: 169, code: '239',name: 'Huyện Thanh Thuỷ', kind: 'Huyện', city_id: 16},
  {id: 170, code: '240',name: 'Huyện Tân Sơn', kind: 'Huyện', city_id: 16},
  {id: 171, code: '243',name: 'Thành phố Vĩnh Yên', kind: 'Thành phố', city_id: 17},
  {id: 172, code: '244',name: 'Thị xã Phúc Yên', kind: 'Thị xã', city_id: 17},
  {id: 173, code: '246',name: 'Huyện Lập Thạch', kind: 'Huyện', city_id: 17},
  {id: 174, code: '247',name: 'Huyện Tam Dương', kind: 'Huyện', city_id: 17},
  {id: 175, code: '248',name: 'Huyện Tam Đảo', kind: 'Huyện', city_id: 17},
  {id: 176, code: '249',name: 'Huyện Bình Xuyên', kind: 'Huyện', city_id: 17},
  {id: 177, code: '250',name: 'Huyện Mê Linh', kind: 'Huyện', city_id: 1},
  {id: 178, code: '251',name: 'Huyện Yên Lạc', kind: 'Huyện', city_id: 17},
  {id: 179, code: '252',name: 'Huyện Vĩnh Tường', kind: 'Huyện', city_id: 17},
  {id: 180, code: '253',name: 'Huyện Sông Lô', kind: 'Huyện', city_id: 17},
  {id: 181, code: '256',name: 'Thành phố Bắc Ninh', kind: 'Thành phố', city_id: 18},
  {id: 182, code: '258',name: 'Huyện Yên Phong', kind: 'Huyện', city_id: 18},
  {id: 183, code: '259',name: 'Huyện Quế Võ', kind: 'Huyện', city_id: 18},
  {id: 184, code: '260',name: 'Huyện Tiên Du', kind: 'Huyện', city_id: 18},
  {id: 185, code: '261',name: 'Thị xã Từ Sơn', kind: 'Thị xã', city_id: 18},
  {id: 186, code: '262',name: 'Huyện Thuận Thành', kind: 'Huyện', city_id: 18},
  {id: 187, code: '263',name: 'Huyện Gia Bình', kind: 'Huyện', city_id: 18},
  {id: 188, code: '264',name: 'Huyện Lương Tài', kind: 'Huyện', city_id: 18},
  {id: 189, code: '268',name: 'Quận Hà Đông', kind: 'Quận', city_id: 1},
  {id: 190, code: '269',name: 'Thị xã Sơn Tây', kind: 'Thị xã', city_id: 1},
  {id: 191, code: '271',name: 'Huyện Ba Vì', kind: 'Huyện', city_id: 1},
  {id: 192, code: '272',name: 'Huyện Phúc Thọ', kind: 'Huyện', city_id: 1},
  {id: 193, code: '273',name: 'Huyện Đan Phượng', kind: 'Huyện', city_id: 1},
  {id: 194, code: '274',name: 'Huyện Hoài Đức', kind: 'Huyện', city_id: 1},
  {id: 195, code: '275',name: 'Huyện Quốc Oai', kind: 'Huyện', city_id: 1},
  {id: 196, code: '276',name: 'Huyện Thạch Thất', kind: 'Huyện', city_id: 1},
  {id: 197, code: '277',name: 'Huyện Chương Mỹ', kind: 'Huyện', city_id: 1},
  {id: 198, code: '278',name: 'Huyện Thanh Oai', kind: 'Huyện', city_id: 1},
  {id: 199, code: '279',name: 'Huyện Thường Tín', kind: 'Huyện', city_id: 1},
  {id: 200, code: '280',name: 'Huyện Phú Xuyên', kind: 'Huyện', city_id: 1},
  {id: 201, code: '281',name: 'Huyện Ứng Hòa', kind: 'Huyện', city_id: 1},
  {id: 202, code: '282',name: 'Huyện Mỹ Đức', kind: 'Huyện', city_id: 1},
  {id: 203, code: '288',name: 'Thành phố Hải Dương', kind: 'Thành phố', city_id: 19},
  {id: 204, code: '290',name: 'Thị xã Chí Linh', kind: 'Thị xã', city_id: 19},
  {id: 205, code: '291',name: 'Huyện Nam Sách', kind: 'Huyện', city_id: 19},
  {id: 206, code: '292',name: 'Huyện Kinh Môn', kind: 'Huyện', city_id: 19},
  {id: 207, code: '293',name: 'Huyện Kim Thành', kind: 'Huyện', city_id: 19},
  {id: 208, code: '294',name: 'Huyện Thanh Hà', kind: 'Huyện', city_id: 19},
  {id: 209, code: '295',name: 'Huyện Cẩm Giàng', kind: 'Huyện', city_id: 19},
  {id: 210, code: '296',name: 'Huyện Bình Giang', kind: 'Huyện', city_id: 19},
  {id: 211, code: '297',name: 'Huyện Gia Lộc', kind: 'Huyện', city_id: 19},
  {id: 212, code: '298',name: 'Huyện Tứ Kỳ', kind: 'Huyện', city_id: 19},
  {id: 213, code: '299',name: 'Huyện Ninh Giang', kind: 'Huyện', city_id: 19},
  {id: 214, code: '300',name: 'Huyện Thanh Miện', kind: 'Huyện', city_id: 19},
  # {id: 215, code: '303',name: 'Quận Hồng Bàng', kind: 'Quận', city_id: '31'},
  # {id: 216, code: '304',name: 'Quận Ngô Quyền', kind: 'Quận', city_id: '31'},
  # {id: , code: '305',name: 'Quận Lê Chân', kind: 'Quận', city_id: '31'},
  # {id: , code: '306',name: 'Quận Hải An', kind: 'Quận', city_id: '31'},
  # {id: , code: '307',name: 'Quận Kiến An', kind: 'Quận', city_id: '31'},
  # {id: , code: '308',name: 'Quận Đồ Sơn', kind: 'Quận', city_id: '31'},
  # {id: , code: '309',name: 'Quận Dương Kinh', kind: 'Quận', city_id: '31'},
  # {id: , code: '311',name: 'Huyện Thuỷ Nguyên', kind: 'Huyện', city_id: '31'},
  # {id: , code: '312',name: 'Huyện An Dương', kind: 'Huyện', city_id: '31'},
  # {id: , code: '313',name: 'Huyện An Lão', kind: 'Huyện', city_id: '31'},
  # {id: , code: '314',name: 'Huyện Kiến Thuỵ', kind: 'Huyện', city_id: '31'},
  # {id: , code: '315',name: 'Huyện Tiên Lãng', kind: 'Huyện', city_id: '31'},
  # {id: , code: '316',name: 'Huyện Vĩnh Bảo', kind: 'Huyện', city_id: '31'},
  # {id: , code: '317',name: 'Huyện Cát Hải', kind: 'Huyện', city_id: '31'},
  # {id: , code: '318',name: 'Huyện Bạch Long Vĩ', kind: 'Huyện', city_id: '31'},
  # {id: , code: '323',name: 'Thành phố Hưng Yên', kind: 'Thành phố', city_id: '33'},
  # {id: , code: '325',name: 'Huyện Văn Lâm', kind: 'Huyện', city_id: '33'},
  # {id: , code: '326',name: 'Huyện Văn Giang', kind: 'Huyện', city_id: '33'},
  # {id: , code: '327',name: 'Huyện Yên Mỹ', kind: 'Huyện', city_id: '33'},
  # {id: , code: '328',name: 'Huyện Mỹ Hào', kind: 'Huyện', city_id: '33'},
  # {id: , code: '329',name: 'Huyện Ân Thi', kind: 'Huyện', city_id: '33'},
  # {id: , code: '330',name: 'Huyện Khoái Châu', kind: 'Huyện', city_id: '33'},
  # {id: , code: '331',name: 'Huyện Kim Động', kind: 'Huyện', city_id: '33'},
  # {id: , code: '332',name: 'Huyện Tiên Lữ', kind: 'Huyện', city_id: '33'},
  # {id: , code: '333',name: 'Huyện Phù Cừ', kind: 'Huyện', city_id: '33'},
  # {id: , code: '336',name: 'Thành phố Thái Bình', kind: 'Thành phố', city_id: '34'},
  # {id: , code: '338',name: 'Huyện Quỳnh Phụ', kind: 'Huyện', city_id: '34'},
  # {id: , code: '339',name: 'Huyện Hưng Hà', kind: 'Huyện', city_id: '34'},
  # {id: , code: '340',name: 'Huyện Đông Hưng', kind: 'Huyện', city_id: '34'},
  # {id: , code: '341',name: 'Huyện Thái Thụy', kind: 'Huyện', city_id: '34'},
  # {id: , code: '342',name: 'Huyện Tiền Hải', kind: 'Huyện', city_id: '34'},
  # {id: , code: '343',name: 'Huyện Kiến Xương', kind: 'Huyện', city_id: '34'},
  # {id: , code: '344',name: 'Huyện Vũ Thư', kind: 'Huyện', city_id: '34'},
  # {id: , code: '347',name: 'Thành phố Phủ Lý', kind: 'Thành phố', city_id: '35'},
  # {id: , code: '349',name: 'Huyện Duy Tiên', kind: 'Huyện', city_id: '35'},
  # {id: , code: '350',name: 'Huyện Kim Bảng', kind: 'Huyện', city_id: '35'},
  # {id: , code: '351',name: 'Huyện Thanh Liêm', kind: 'Huyện', city_id: '35'},
  # {id: , code: '352',name: 'Huyện Bình Lục', kind: 'Huyện', city_id: '35'},
  # {id: , code: '353',name: 'Huyện Lý Nhân', kind: 'Huyện', city_id: '35'},
  # {id: , code: '356',name: 'Thành phố Nam Định', kind: 'Thành phố', city_id: '36'},
  # {id: , code: '358',name: 'Huyện Mỹ Lộc', kind: 'Huyện', city_id: '36'},
  # {id: , code: '359',name: 'Huyện Vụ Bản', kind: 'Huyện', city_id: '36'},
  # {id: , code: '360',name: 'Huyện Ý Yên', kind: 'Huyện', city_id: '36'},
  # {id: , code: '361',name: 'Huyện Nghĩa Hưng', kind: 'Huyện', city_id: '36'},
  # {id: , code: '362',name: 'Huyện Nam Trực', kind: 'Huyện', city_id: '36'},
  # {id: , code: '363',name: 'Huyện Trực Ninh', kind: 'Huyện', city_id: '36'},
  # {id: , code: '364',name: 'Huyện Xuân Trường', kind: 'Huyện', city_id: '36'},
  # {id: , code: '365',name: 'Huyện Giao Thủy', kind: 'Huyện', city_id: '36'},
  # {id: , code: '366',name: 'Huyện Hải Hậu', kind: 'Huyện', city_id: '36'},
  # {id: , code: '369',name: 'Thành phố Ninh Bình', kind: 'Thành phố', city_id: '37'},
  # {id: , code: '370',name: 'Thành phố Tam Điệp', kind: 'Thành phố', city_id: '37'},
  # {id: , code: '372',name: 'Huyện Nho Quan', kind: 'Huyện', city_id: '37'},
  # {id: , code: '373',name: 'Huyện Gia Viễn', kind: 'Huyện', city_id: '37'},
  # {id: , code: '374',name: 'Huyện Hoa Lư', kind: 'Huyện', city_id: '37'},
  # {id: , code: '375',name: 'Huyện Yên Khánh', kind: 'Huyện', city_id: '37'},
  # {id: , code: '376',name: 'Huyện Kim Sơn', kind: 'Huyện', city_id: '37'},
  # {id: , code: '377',name: 'Huyện Yên Mô', kind: 'Huyện', city_id: '37'},
  # {id: , code: '380',name: 'Thành phố Thanh Hóa', kind: 'Thành phố', city_id: '38'},
  # {id: , code: '381',name: 'Thị xã Bỉm Sơn', kind: 'Thị xã', city_id: '38'},
  # {id: , code: '382',name: 'Thị xã Sầm Sơn', kind: 'Thị xã', city_id: '38'},
  # {id: , code: '384',name: 'Huyện Mường Lát', kind: 'Huyện', city_id: '38'},
  # {id: , code: '385',name: 'Huyện Quan Hóa', kind: 'Huyện', city_id: '38'},
  # {id: , code: '386',name: 'Huyện Bá Thước', kind: 'Huyện', city_id: '38'},
  # {id: , code: '387',name: 'Huyện Quan Sơn', kind: 'Huyện', city_id: '38'},
  # {id: , code: '388',name: 'Huyện Lang Chánh', kind: 'Huyện', city_id: '38'},
  # {id: , code: '389',name: 'Huyện Ngọc Lặc', kind: 'Huyện', city_id: '38'},
  # {id: , code: '390',name: 'Huyện Cẩm Thủy', kind: 'Huyện', city_id: '38'},
  # {id: , code: '391',name: 'Huyện Thạch Thành', kind: 'Huyện', city_id: '38'},
  # {id: , code: '392',name: 'Huyện Hà Trung', kind: 'Huyện', city_id: '38'},
  # {id: , code: '393',name: 'Huyện Vĩnh Lộc', kind: 'Huyện', city_id: '38'},
  # {id: , code: '394',name: 'Huyện Yên Định', kind: 'Huyện', city_id: '38'},
  # {id: , code: '395',name: 'Huyện Thọ Xuân', kind: 'Huyện', city_id: '38'},
  # {id: , code: '396',name: 'Huyện Thường Xuân', kind: 'Huyện', city_id: '38'},
  # {id: , code: '397',name: 'Huyện Triệu Sơn', kind: 'Huyện', city_id: '38'},
  # {id: , code: '398',name: 'Huyện Thiệu Hóa', kind: 'Huyện', city_id: '38'},
  # {id: , code: '399',name: 'Huyện Hoằng Hóa', kind: 'Huyện', city_id: '38'},
  # {id: , code: '400',name: 'Huyện Hậu Lộc', kind: 'Huyện', city_id: '38'},
  # {id: , code: '401',name: 'Huyện Nga Sơn', kind: 'Huyện', city_id: '38'},
  # {id: , code: '402',name: 'Huyện Như Xuân', kind: 'Huyện', city_id: '38'},
  # {id: , code: '403',name: 'Huyện Như Thanh', kind: 'Huyện', city_id: '38'},
  # {id: , code: '404',name: 'Huyện Nông Cống', kind: 'Huyện', city_id: '38'},
  # {id: , code: '405',name: 'Huyện Đông Sơn', kind: 'Huyện', city_id: '38'},
  # {id: , code: '406',name: 'Huyện Quảng Xương', kind: 'Huyện', city_id: '38'},
  # {id: , code: '407',name: 'Huyện Tĩnh Gia', kind: 'Huyện', city_id: '38'},
  # {id: , code: '412',name: 'Thành phố Vinh', kind: 'Thành phố', city_id: '40'},
  # {id: , code: '413',name: 'Thị xã Cửa Lò', kind: 'Thị xã', city_id: '40'},
  # {id: , code: '414',name: 'Thị xã Thái Hoà', kind: 'Thị xã', city_id: '40'},
  # {id: , code: '415',name: 'Huyện Quế Phong', kind: 'Huyện', city_id: '40'},
  # {id: , code: '416',name: 'Huyện Quỳ Châu', kind: 'Huyện', city_id: '40'},
  # {id: , code: '417',name: 'Huyện Kỳ Sơn', kind: 'Huyện', city_id: '40'},
  # {id: , code: '418',name: 'Huyện Tương Dương', kind: 'Huyện', city_id: '40'},
  # {id: , code: '419',name: 'Huyện Nghĩa Đàn', kind: 'Huyện', city_id: '40'},
  # {id: , code: '420',name: 'Huyện Quỳ Hợp', kind: 'Huyện', city_id: '40'},
  # {id: , code: '421',name: 'Huyện Quỳnh Lưu', kind: 'Huyện', city_id: '40'},
  # {id: , code: '422',name: 'Huyện Con Cuông', kind: 'Huyện', city_id: '40'},
  # {id: , code: '423',name: 'Huyện Tân Kỳ', kind: 'Huyện', city_id: '40'},
  # {id: , code: '424',name: 'Huyện Anh Sơn', kind: 'Huyện', city_id: '40'},
  # {id: , code: '425',name: 'Huyện Diễn Châu', kind: 'Huyện', city_id: '40'},
  # {id: , code: '426',name: 'Huyện Yên Thành', kind: 'Huyện', city_id: '40'},
  # {id: , code: '427',name: 'Huyện Đô Lương', kind: 'Huyện', city_id: '40'},
  # {id: , code: '428',name: 'Huyện Thanh Chương', kind: 'Huyện', city_id: '40'},
  # {id: , code: '429',name: 'Huyện Nghi Lộc', kind: 'Huyện', city_id: '40'},
  # {id: , code: '430',name: 'Huyện Nam Đàn', kind: 'Huyện', city_id: '40'},
  # {id: , code: '431',name: 'Huyện Hưng Nguyên', kind: 'Huyện', city_id: '40'},
  # {id: , code: '432',name: 'Thị xã Hoàng Mai', kind: 'Thị xã', city_id: '40'},
  # {id: , code: '436',name: 'Thành phố Hà Tĩnh', kind: 'Thành phố', city_id: '42'},
  # {id: , code: '437',name: 'Thị xã Hồng Lĩnh', kind: 'Thị xã', city_id: '42'},
  # {id: , code: '439',name: 'Huyện Hương Sơn', kind: 'Huyện', city_id: '42'},
  # {id: , code: '440',name: 'Huyện Đức Thọ', kind: 'Huyện', city_id: '42'},
  # {id: , code: '441',name: 'Huyện Vũ Quang', kind: 'Huyện', city_id: '42'},
  # {id: , code: '442',name: 'Huyện Nghi Xuân', kind: 'Huyện', city_id: '42'},
  # {id: , code: '443',name: 'Huyện Can Lộc', kind: 'Huyện', city_id: '42'},
  # {id: , code: '444',name: 'Huyện Hương Khê', kind: 'Huyện', city_id: '42'},
  # {id: , code: '445',name: 'Huyện Thạch Hà', kind: 'Huyện', city_id: '42'},
  # {id: , code: '446',name: 'Huyện Cẩm Xuyên', kind: 'Huyện', city_id: '42'},
  # {id: , code: '447',name: 'Huyện Kỳ Anh', kind: 'Huyện', city_id: '42'},
  # {id: , code: '448',name: 'Huyện Lộc Hà', kind: 'Huyện', city_id: '42'},
  # {id: , code: '449',name: 'Thị xã Kỳ Anh', kind: 'Thị xã', city_id: '42'},
  # {id: , code: '450',name: 'Thành Phố Đồng Hới', kind: 'Thành phố', city_id: '44'},
  # {id: , code: '452',name: 'Huyện Minh Hóa', kind: 'Huyện', city_id: '44'},
  # {id: , code: '453',name: 'Huyện Tuyên Hóa', kind: 'Huyện', city_id: '44'},
  # {id: , code: '454',name: 'Huyện Quảng Trạch', kind: 'Thị xã', city_id: '44'},
  # {id: , code: '455',name: 'Huyện Bố Trạch', kind: 'Huyện', city_id: '44'},
  # {id: , code: '456',name: 'Huyện Quảng Ninh', kind: 'Huyện', city_id: '44'},
  # {id: , code: '457',name: 'Huyện Lệ Thủy', kind: 'Huyện', city_id: '44'},
  # {id: , code: '458',name: 'Thị xã Ba Đồn', kind: 'Huyện', city_id: '44'},
  # {id: , code: '461',name: 'Thành phố Đông Hà', kind: 'Thành phố', city_id: '45'},
  # {id: , code: '462',name: 'Thị xã Quảng Trị', kind: 'Thị xã', city_id: '45'},
  # {id: , code: '464',name: 'Huyện Vĩnh Linh', kind: 'Huyện', city_id: '45'},
  # {id: , code: '465',name: 'Huyện Hướng Hóa', kind: 'Huyện', city_id: '45'},
  # {id: , code: '466',name: 'Huyện Gio Linh', kind: 'Huyện', city_id: '45'},
  # {id: , code: '467',name: 'Huyện Đa Krông', kind: 'Huyện', city_id: '45'},
  # {id: , code: '468',name: 'Huyện Cam Lộ', kind: 'Huyện', city_id: '45'},
  # {id: , code: '469',name: 'Huyện Triệu Phong', kind: 'Huyện', city_id: '45'},
  # {id: , code: '470',name: 'Huyện Hải Lăng', kind: 'Huyện', city_id: '45'},
  # {id: , code: '471',name: 'Huyện Cồn Cỏ', kind: 'Huyện', city_id: '45'},
  # {id: , code: '474',name: 'Thành phố Huế', kind: 'Thành phố', city_id: '46'},
  # {id: , code: '476',name: 'Huyện Phong Điền', kind: 'Huyện', city_id: '46'},
  # {id: , code: '477',name: 'Huyện Quảng Điền', kind: 'Huyện', city_id: '46'},
  # {id: , code: '478',name: 'Huyện Phú Vang', kind: 'Huyện', city_id: '46'},
  # {id: , code: '479',name: 'Thị xã Hương Thủy', kind: 'Thị xã', city_id: '46'},
  # {id: , code: '480',name: 'Thị xã Hương Trà', kind: 'Thị xã', city_id: '46'},
  # {id: , code: '481',name: 'Huyện A Lưới', kind: 'Huyện', city_id: '46'},
  # {id: , code: '482',name: 'Huyện Phú Lộc', kind: 'Huyện', city_id: '46'},
  # {id: , code: '483',name: 'Huyện Nam Đông', kind: 'Huyện', city_id: '46'},
  # {id: , code: '490',name: 'Quận Liên Chiểu', kind: 'Quận', city_id: '48'},
  # {id: , code: '491',name: 'Quận Thanh Khê', kind: 'Quận', city_id: '48'},
  # {id: , code: '492',name: 'Quận Hải Châu', kind: 'Quận', city_id: '48'},
  # {id: , code: '493',name: 'Quận Sơn Trà', kind: 'Quận', city_id: '48'},
  # {id: , code: '494',name: 'Quận Ngũ Hành Sơn', kind: 'Quận', city_id: '48'},
  # {id: , code: '495',name: 'Quận Cẩm Lệ', kind: 'Quận', city_id: '48'},
  # {id: , code: '497',name: 'Huyện Hòa Vang', kind: 'Huyện', city_id: '48'},
  # {id: , code: '498',name: 'Huyện Hoàng Sa', kind: 'Huyện', city_id: '48'},
  # {id: , code: '502',name: 'Thành phố Tam Kỳ', kind: 'Thành phố', city_id: '49'},
  # {id: , code: '503',name: 'Thành phố Hội An', kind: 'Thành phố', city_id: '49'},
  # {id: , code: '504',name: 'Huyện Tây Giang', kind: 'Huyện', city_id: '49'},
  # {id: , code: '505',name: 'Huyện Đông Giang', kind: 'Huyện', city_id: '49'},
  # {id: , code: '506',name: 'Huyện Đại Lộc', kind: 'Huyện', city_id: '49'},
  # {id: , code: '507',name: 'Thị xã Điện Bàn', kind: 'Thị xã', city_id: '49'},
  # {id: , code: '508',name: 'Huyện Duy Xuyên', kind: 'Huyện', city_id: '49'},
  # {id: , code: '509',name: 'Huyện Quế Sơn', kind: 'Huyện', city_id: '49'},
  # {id: , code: '510',name: 'Huyện Nam Giang', kind: 'Huyện', city_id: '49'},
  # {id: , code: '511',name: 'Huyện Phước Sơn', kind: 'Huyện', city_id: '49'},
  # {id: , code: '512',name: 'Huyện Hiệp Đức', kind: 'Huyện', city_id: '49'},
  # {id: , code: '513',name: 'Huyện Thăng Bình', kind: 'Huyện', city_id: '49'},
  # {id: , code: '514',name: 'Huyện Tiên Phước', kind: 'Huyện', city_id: '49'},
  # {id: , code: '515',name: 'Huyện Bắc Trà My', kind: 'Huyện', city_id: '49'},
  # {id: , code: '516',name: 'Huyện Nam Trà My', kind: 'Huyện', city_id: '49'},
  # {id: , code: '517',name: 'Huyện Núi Thành', kind: 'Huyện', city_id: '49'},
  # {id: , code: '518',name: 'Huyện Phú Ninh', kind: 'Huyện', city_id: '49'},
  # {id: , code: '519',name: 'Huyện Nông Sơn', kind: 'Huyện', city_id: '49'},
  # {id: , code: '522',name: 'Thành phố Quảng Ngãi', kind: 'Thành phố', city_id: '51'},
  # {id: , code: '524',name: 'Huyện Bình Sơn', kind: 'Huyện', city_id: '51'},
  # {id: , code: '525',name: 'Huyện Trà Bồng', kind: 'Huyện', city_id: '51'},
  # {id: , code: '526',name: 'Huyện Tây Trà', kind: 'Huyện', city_id: '51'},
  # {id: , code: '527',name: 'Huyện Sơn Tịnh', kind: 'Huyện', city_id: '51'},
  # {id: , code: '528',name: 'Huyện Tư Nghĩa', kind: 'Huyện', city_id: '51'},
  # {id: , code: '529',name: 'Huyện Sơn Hà', kind: 'Huyện', city_id: '51'},
  # {id: , code: '530',name: 'Huyện Sơn Tây', kind: 'Huyện', city_id: '51'},
  # {id: , code: '531',name: 'Huyện Minh Long', kind: 'Huyện', city_id: '51'},
  # {id: , code: '532',name: 'Huyện Nghĩa Hành', kind: 'Huyện', city_id: '51'},
  # {id: , code: '533',name: 'Huyện Mộ Đức', kind: 'Huyện', city_id: '51'},
  # {id: , code: '534',name: 'Huyện Đức Phổ', kind: 'Huyện', city_id: '51'},
  # {id: , code: '535',name: 'Huyện Ba Tơ', kind: 'Huyện', city_id: '51'},
  # {id: , code: '536',name: 'Huyện Lý Sơn', kind: 'Huyện', city_id: '51'},
  # {id: , code: '540',name: 'Thành phố Qui Nhơn', kind: 'Thành phố', city_id: '52'},
  # {id: , code: '542',name: 'Huyện An Lão', kind: 'Huyện', city_id: '52'},
  # {id: , code: '543',name: 'Huyện Hoài Nhơn', kind: 'Huyện', city_id: '52'},
  # {id: , code: '544',name: 'Huyện Hoài Ân', kind: 'Huyện', city_id: '52'},
  # {id: , code: '545',name: 'Huyện Phù Mỹ', kind: 'Huyện', city_id: '52'},
  # {id: , code: '546',name: 'Huyện Vĩnh Thạnh', kind: 'Huyện', city_id: '52'},
  # {id: , code: '547',name: 'Huyện Tây Sơn', kind: 'Huyện', city_id: '52'},
  # {id: , code: '548',name: 'Huyện Phù Cát', kind: 'Huyện', city_id: '52'},
  # {id: , code: '549',name: 'Thị xã An Nhơn', kind: 'Thị xã', city_id: '52'},
  # {id: , code: '550',name: 'Huyện Tuy Phước', kind: 'Huyện', city_id: '52'},
  # {id: , code: '551',name: 'Huyện Vân Canh', kind: 'Huyện', city_id: '52'},
  # {id: , code: '555',name: 'Thành phố Tuy Hoà', kind: 'Thành phố', city_id: '54'},
  # {id: , code: '557',name: 'Thị xã Sông Cầu', kind: 'Thị xã', city_id: '54'},
  # {id: , code: '558',name: 'Huyện Đồng Xuân', kind: 'Huyện', city_id: '54'},
  # {id: , code: '559',name: 'Huyện Tuy An', kind: 'Huyện', city_id: '54'},
  # {id: , code: '560',name: 'Huyện Sơn Hòa', kind: 'Huyện', city_id: '54'},
  # {id: , code: '561',name: 'Huyện Sông Hinh', kind: 'Huyện', city_id: '54'},
  # {id: , code: '562',name: 'Huyện Tây Hoà', kind: 'Huyện', city_id: '54'},
  # {id: , code: '563',name: 'Huyện Phú Hoà', kind: 'Huyện', city_id: '54'},
  # {id: , code: '564',name: 'Huyện Đông Hòa', kind: 'Huyện', city_id: '54'},
  # {id: , code: '568',name: 'Thành phố Nha Trang', kind: 'Thành phố', city_id: '56'},
  # {id: , code: '569',name: 'Thành phố Cam Ranh', kind: 'Thành phố', city_id: '56'},
  # {id: , code: '570',name: 'Huyện Cam Lâm', kind: 'Huyện', city_id: '56'},
  # {id: , code: '571',name: 'Huyện Vạn Ninh', kind: 'Huyện', city_id: '56'},
  # {id: , code: '572',name: 'Thị xã Ninh Hòa', kind: 'Thị xã', city_id: '56'},
  # {id: , code: '573',name: 'Huyện Khánh Vĩnh', kind: 'Huyện', city_id: '56'},
  # {id: , code: '574',name: 'Huyện Diên Khánh', kind: 'Huyện', city_id: '56'},
  # {id: , code: '575',name: 'Huyện Khánh Sơn', kind: 'Huyện', city_id: '56'},
  # {id: , code: '576',name: 'Huyện Trường Sa', kind: 'Huyện', city_id: '56'},
  # {id: , code: '582',name: 'Thành phố Phan Rang-Tháp Chàm', kind: 'Thành phố', city_id: '58'},
  # {id: , code: '584',name: 'Huyện Bác Ái', kind: 'Huyện', city_id: '58'},
  # {id: , code: '585',name: 'Huyện Ninh Sơn', kind: 'Huyện', city_id: '58'},
  # {id: , code: '586',name: 'Huyện Ninh Hải', kind: 'Huyện', city_id: '58'},
  # {id: , code: '587',name: 'Huyện Ninh Phước', kind: 'Huyện', city_id: '58'},
  # {id: , code: '588',name: 'Huyện Thuận Bắc', kind: 'Huyện', city_id: '58'},
  # {id: , code: '589',name: 'Huyện Thuận Nam', kind: 'Huyện', city_id: '58'},
  # {id: , code: '593',name: 'Thành phố Phan Thiết', kind: 'Thành phố', city_id: '60'},
  # {id: , code: '594',name: 'Thị xã La Gi', kind: 'Thị xã', city_id: '60'},
  # {id: , code: '595',name: 'Huyện Tuy Phong', kind: 'Huyện', city_id: '60'},
  # {id: , code: '596',name: 'Huyện Bắc Bình', kind: 'Huyện', city_id: '60'},
  # {id: , code: '597',name: 'Huyện Hàm Thuận Bắc', kind: 'Huyện', city_id: '60'},
  # {id: , code: '598',name: 'Huyện Hàm Thuận Nam', kind: 'Huyện', city_id: '60'},
  # {id: , code: '599',name: 'Huyện Tánh Linh', kind: 'Huyện', city_id: '60'},
  # {id: , code: '600',name: 'Huyện Đức Linh', kind: 'Huyện', city_id: '60'},
  # {id: , code: '601',name: 'Huyện Hàm Tân', kind: 'Huyện', city_id: '60'},
  # {id: , code: '602',name: 'Huyện Phú Quí', kind: 'Huyện', city_id: '60'},
  # {id: , code: '608',name: 'Thành phố Kon Tum', kind: 'Thành phố', city_id: '62'},
  # {id: , code: '610',name: 'Huyện Đắk Glei', kind: 'Huyện', city_id: '62'},
  # {id: , code: '611',name: 'Huyện Ngọc Hồi', kind: 'Huyện', city_id: '62'},
  # {id: , code: '612',name: 'Huyện Đắk Tô', kind: 'Huyện', city_id: '62'},
  # {id: , code: '613',name: 'Huyện Kon Plông', kind: 'Huyện', city_id: '62'},
  # {id: , code: '614',name: 'Huyện Kon Rẫy', kind: 'Huyện', city_id: '62'},
  # {id: , code: '615',name: 'Huyện Đắk Hà', kind: 'Huyện', city_id: '62'},
  # {id: , code: '616',name: 'Huyện Sa Thầy', kind: 'Huyện', city_id: '62'},
  # {id: , code: '617',name: 'Huyện Tu Mơ Rông', kind: 'Huyện', city_id: '62'},
  # {id: , code: '618',name: 'Huyện Ia H\' Drai', kind: 'Huyện', city_id: '62'},
  # {id: , code: '622',name: 'Thành phố Pleiku', kind: 'Thành phố', city_id: '64'},
  # {id: , code: '623',name: 'Thị xã An Khê', kind: 'Thị xã', city_id: '64'},
  # {id: , code: '624',name: 'Thị xã Ayun Pa', kind: 'Thị xã', city_id: '64'},
  # {id: , code: '625',name: 'Huyện KBang', kind: 'Huyện', city_id: '64'},
  # {id: , code: '626',name: 'Huyện Đăk Đoa', kind: 'Huyện', city_id: '64'},
  # {id: , code: '627',name: 'Huyện Chư Păh', kind: 'Huyện', city_id: '64'},
  # {id: , code: '628',name: 'Huyện Ia Grai', kind: 'Huyện', city_id: '64'},
  # {id: , code: '629',name: 'Huyện Mang Yang', kind: 'Huyện', city_id: '64'},
  # {id: , code: '630',name: 'Huyện Kông Chro', kind: 'Huyện', city_id: '64'},
  # {id: , code: '631',name: 'Huyện Đức Cơ', kind: 'Huyện', city_id: '64'},
  # {id: , code: '632',name: 'Huyện Chư Prông', kind: 'Huyện', city_id: '64'},
  # {id: , code: '633',name: 'Huyện Chư Sê', kind: 'Huyện', city_id: '64'},
  # {id: , code: '634',name: 'Huyện Đăk Pơ', kind: 'Huyện', city_id: '64'},
  # {id: , code: '635',name: 'Huyện Ia Pa', kind: 'Huyện', city_id: '64'},
  # {id: , code: '637',name: 'Huyện Krông Pa', kind: 'Huyện', city_id: '64'},
  # {id: , code: '638',name: 'Huyện Phú Thiện', kind: 'Huyện', city_id: '64'},
  # {id: , code: '639',name: 'Huyện Chư Pưh', kind: 'Huyện', city_id: '64'},
  # {id: , code: '643',name: 'Thành phố Buôn Ma Thuột', kind: 'Thành phố', city_id: '66'},
  # {id: , code: '644',name: 'Thị Xã Buôn Hồ', kind: 'Thị xã', city_id: '66'},
  # {id: , code: '645',name: 'Huyện Ea H\'leo', kind: 'Huyện', city_id: '66'},
  # {id: , code: '646',name: 'Huyện Ea Súp', kind: 'Huyện', city_id: '66'},
  # {id: , code: '647', name: 'Huyện Buôn Đôn', kind: 'Huyện', city_id:'66'},
  # {id: , code: '648', name: 'Huyện Cư M\'gar', kind: 'Huyện', city_id:'66'},
  # {id: , code: '649', name: 'Huyện Krông Búk', kind: 'Huyện', city_id:'66'},
  # {id: , code: '650', name: 'Huyện Krông Năng', kind: 'Huyện', city_id:'66'},
  # {id: , code: '651', name: 'Huyện Ea Kar', kind: 'Huyện', city_id:'66'},
  # {id: , code: '652', name: 'Huyện M\'Đrắk', kind: 'Huyện', city_id:'66'},
  # {id: , code: '653', name: 'Huyện Krông Bông', kind: 'Huyện', city_id:'66'},
  # {id: , code: '654', name: 'Huyện Krông Pắc', kind: 'Huyện', city_id:'66'},
  # {id: , code: '655', name: 'Huyện Krông A Na', kind: 'Huyện', city_id:'66'},
  # {id: , code: '656', name: 'Huyện Lắk', kind: 'Huyện', city_id:'66'},
  # {id: , code: '657', name: 'Huyện Cư Kuin', kind: 'Huyện', city_id:'66'},
  # {id: , code: '660', name: 'Thị xã Gia Nghĩa', kind: 'Thị xã', city_id:'67'},
  # {id: , code: '661', name: 'Huyện Đăk Glong', kind: 'Huyện', city_id:'67'},
  # {id: , code: '662', name: 'Huyện Cư Jút', kind: 'Huyện', city_id:'67'},
  # {id: , code: '663', name: 'Huyện Đắk Mil', kind: 'Huyện', city_id:'67'},
  # {id: , code: '664', name: 'Huyện Krông Nô', kind: 'Huyện', city_id:'67'},
  # {id: , code: '665', name: 'Huyện Đắk Song', kind: 'Huyện', city_id:'67'},
  # {id: , code: '666', name: 'Huyện Đắk R\'Lấp', kind: 'Huyện', city_id:'67'},
  # {id: , code: '667', name: 'Huyện Tuy Đức', kind: 'Huyện', city_id:'67'},
  # {id: , code: '672', name: 'Thành phố Đà Lạt', kind: 'Thành phố', city_id:'68'},
  # {id: , code: '673', name: 'Thành phố Bảo Lộc', kind: 'Thành phố', city_id:'68'},
  # {id: , code: '674', name: 'Huyện Đam Rông', kind: 'Huyện', city_id:'68'},
  # {id: , code: '675', name: 'Huyện Lạc Dương', kind: 'Huyện', city_id:'68'},
  # {id: , code: '676', name: 'Huyện Lâm Hà', kind: 'Huyện', city_id:'68'},
  # {id: , code: '677', name: 'Huyện Đơn Dương', kind: 'Huyện', city_id:'68'},
  # {id: , code: '678', name: 'Huyện Đức Trọng', kind: 'Huyện', city_id:'68'},
  # {id: , code: '679', name: 'Huyện Di Linh', kind: 'Huyện', city_id:'68'},
  # {id: , code: '680', name: 'Huyện Bảo Lâm', kind: 'Huyện', city_id:'68'},
  # {id: , code: '681', name: 'Huyện Đạ Huoai', kind: 'Huyện', city_id:'68'},
  # {id: , code: '682', name: 'Huyện Đạ Tẻh', kind: 'Huyện', city_id:'68'},
  # {id: , code: '683', name: 'Huyện Cát Tiên', kind: 'Huyện', city_id:'68'},
  # {id: , code: '688', name: 'Thị xã Phước Long', kind: 'Thị xã', city_id:'70'},
  # {id: , code: '689', name: 'Thị xã Đồng Xoài', kind: 'Thị xã', city_id:'70'},
  # {id: , code: '690', name: 'Thị xã Bình Long', kind: 'Thị xã', city_id:'70'},
  # {id: , code: '691', name: 'Huyện Bù Gia Mập', kind: 'Huyện', city_id:'70'},
  # {id: , code: '692', name: 'Huyện Lộc Ninh', kind: 'Huyện', city_id:'70'},
  # {id: , code: '693', name: 'Huyện Bù Đốp', kind: 'Huyện', city_id:'70'},
  # {id: , code: '694', name: 'Huyện Hớn Quản', kind: 'Huyện', city_id:'70'},
  # {id: , code: '695', name: 'Huyện Đồng Phú', kind: 'Huyện', city_id:'70'},
  # {id: , code: '696', name: 'Huyện Bù Đăng', kind: 'Huyện', city_id:'70'},
  # {id: , code: '697', name: 'Huyện Chơn Thành', kind: 'Huyện', city_id:'70'},
  # {id: , code: '698', name: 'Huyện Phú Riềng', kind: 'Huyện', city_id:'70'},
  # {id: , code: '703', name: 'Thành phố Tây Ninh', kind: 'Thành phố', city_id:'72'},
  # {id: , code: '705', name: 'Huyện Tân Biên', kind: 'Huyện', city_id:'72'},
  # {id: , code: '706', name: 'Huyện Tân Châu', kind: 'Huyện', city_id:'72'},
  # {id: , code: '707', name: 'Huyện Dương Minh Châu', kind: 'Huyện', city_id:'72'},
  # {id: , code: '708', name: 'Huyện Châu Thành', kind: 'Huyện', city_id:'72'},
  # {id: , code: '709', name: 'Huyện Hòa Thành', kind: 'Huyện', city_id:'72'},
  # {id: , code: '710', name: 'Huyện Gò Dầu', kind: 'Huyện', city_id:'72'},
  # {id: , code: '711', name: 'Huyện Bến Cầu', kind: 'Huyện', city_id:'72'},
  # {id: , code: '712', name: 'Huyện Trảng Bàng', kind: 'Huyện', city_id:'72'},
  # {id: , code: '718', name: 'Thành phố Thủ Dầu Một', kind: 'Thành phố', city_id:'74'},
  # {id: , code: '719', name: 'Huyện Bàu Bàng', kind: 'Huyện', city_id:'74'},
  # {id: , code: '720', name: 'Huyện Dầu Tiếng', kind: 'Huyện', city_id:'74'},
  # {id: , code: '721', name: 'Thị xã Bến Cát', kind: 'Thị xã', city_id:'74'},
  # {id: , code: '722', name: 'Huyện Phú Giáo', kind: 'Huyện', city_id:'74'},
  # {id: , code: '723', name: 'Thị xã Tân Uyên', kind: 'Thị xã', city_id:'74'},
  # {id: , code: '724', name: 'Thị xã Dĩ An', kind: 'Thị xã', city_id:'74'},
  # {id: , code: '725', name: 'Thị xã Thuận An', kind: 'Thị xã', city_id:'74'},
  # {id: , code: '726', name: 'Huyện Bắc Tân Uyên', kind: 'Huyện', city_id:'74'},
  # {id: , code: '731', name: 'Thành phố Biên Hòa', kind: 'Thành phố', city_id:'75'},
  # {id: , code: '732', name: 'Thị xã Long Khánh', kind: 'Thị xã', city_id:'75'},
  # {id: , code: '734',name: 'Huyện Tân Phú', kind: 'Huyện', city_id: '75'},
  # {id: , code: '735',name: 'Huyện Vĩnh Cửu', kind: 'Huyện', city_id: '75'},
  # {id: , code: '736',name: 'Huyện Định Quán', kind: 'Huyện', city_id: '75'},
  # {id: , code: '737',name: 'Huyện Trảng Bom', kind: 'Huyện', city_id: '75'},
  # {id: , code: '738',name: 'Huyện Thống Nhất', kind: 'Huyện', city_id: '75'},
  # {id: , code: '739',name: 'Huyện Cẩm Mỹ', kind: 'Huyện', city_id: '75'},
  # {id: , code: '740',name: 'Huyện Long Thành', kind: 'Huyện', city_id: '75'},
  # {id: , code: '741',name: 'Huyện Xuân Lộc', kind: 'Huyện', city_id: '75'},
  # {id: , code: '742',name: 'Huyện Nhơn Trạch', kind: 'Huyện', city_id: '75'},
  # {id: , code: '747',name: 'Thành phố Vũng Tàu', kind: 'Thành phố', city_id: '77'},
  # {id: , code: '748',name: 'Thành phố Bà Rịa', kind: 'Thành phố', city_id: '77'},
  # {id: , code: '750',name: 'Huyện Châu Đức', kind: 'Huyện', city_id: '77'},
  # {id: , code: '751',name: 'Huyện Xuyên Mộc', kind: 'Huyện', city_id: '77'},
  # {id: , code: '752',name: 'Huyện Long Điền', kind: 'Huyện', city_id: '77'},
  # {id: , code: '753',name: 'Huyện Đất Đỏ', kind: 'Huyện', city_id: '77'},
  # {id: , code: '754',name: 'Huyện Tân Thành', kind: 'Huyện', city_id: '77'},
  # {id: , code: '755',name: 'Huyện Côn Đảo', kind: 'Huyện', city_id: '77'},
  # {id: , code: '760',name: 'Quận 1', kind: 'Quận', city_id: '79'},
  # {id: , code: '761',name: 'Quận 12', kind: 'Quận', city_id: '79'},
  # {id: , code: '762',name: 'Quận Thủ Đức', kind: 'Quận', city_id: '79'},
  # {id: , code: '763',name: 'Quận 9', kind: 'Quận', city_id: '79'},
  # {id: , code: '764',name: 'Quận Gò Vấp', kind: 'Quận', city_id: '79'},
  # {id: , code: '765',name: 'Quận Bình Thạnh', kind: 'Quận', city_id: '79'},
  # {id: , code: '766',name: 'Quận Tân Bình', kind: 'Quận', city_id: '79'},
  # {id: , code: '767',name: 'Quận Tân Phú', kind: 'Quận', city_id: '79'},
  # {id: , code: '768',name: 'Quận Phú Nhuận', kind: 'Quận', city_id: '79'},
  # {id: , code: '769',name: 'Quận 2', kind: 'Quận', city_id: '79'},
  # {id: , code: '770',name: 'Quận 3', kind: 'Quận', city_id: '79'},
  # {id: , code: '771',name: 'Quận 10', kind: 'Quận', city_id: '79'},
  # {id: , code: '772',name: 'Quận 11', kind: 'Quận', city_id: '79'},
  # {id: , code: '773',name: 'Quận 4', kind: 'Quận', city_id: '79'},
  # {id: , code: '774',name: 'Quận 5', kind: 'Quận', city_id: '79'},
  # {id: , code: '775',name: 'Quận 6', kind: 'Quận', city_id: '79'},
  # {id: , code: '776',name: 'Quận 8', kind: 'Quận', city_id: '79'},
  # {id: , code: '777',name: 'Quận Bình Tân', kind: 'Quận', city_id: '79'},
  # {id: , code: '778',name: 'Quận 7', kind: 'Quận', city_id: '79'},
  # {id: , code: '783',name: 'Huyện Củ Chi', kind: 'Huyện', city_id: '79'},
  # {id: , code: '784',name: 'Huyện Hóc Môn', kind: 'Huyện', city_id: '79'},
  # {id: , code: '785',name: 'Huyện Bình Chánh', kind: 'Huyện', city_id: '79'},
  # {id: , code: '786',name: 'Huyện Nhà Bè', kind: 'Huyện', city_id: '79'},
  # {id: , code: '787',name: 'Huyện Cần Giờ', kind: 'Huyện', city_id: '79'},
  # {id: , code: '794',name: 'Thành phố Tân An', kind: 'Thành phố', city_id: '80'},
  # {id: , code: '795',name: 'Thị xã Kiến Tường', kind: 'Thị xã', city_id: '80'},
  # {id: , code: '796',name: 'Huyện Tân Hưng', kind: 'Huyện', city_id: '80'},
  # {id: , code: '797',name: 'Huyện Vĩnh Hưng', kind: 'Huyện', city_id: '80'},
  # {id: , code: '798',name: 'Huyện Mộc Hóa', kind: 'Huyện', city_id: '80'},
  # {id: , code: '799',name: 'Huyện Tân Thạnh', kind: 'Huyện', city_id: '80'},
  # {id: , code: '800',name: 'Huyện Thạnh Hóa', kind: 'Huyện', city_id: '80'},
  # {id: , code: '801',name: 'Huyện Đức Huệ', kind: 'Huyện', city_id: '80'},
  # {id: , code: '802',name: 'Huyện Đức Hòa', kind: 'Huyện', city_id: '80'},
  # {id: , code: '803',name: 'Huyện Bến Lức', kind: 'Huyện', city_id: '80'},
  # {id: , code: '804',name: 'Huyện Thủ Thừa', kind: 'Huyện', city_id: '80'},
  # {id: , code: '805',name: 'Huyện Tân Trụ', kind: 'Huyện', city_id: '80'},
  # {id: , code: '806',name: 'Huyện Cần Đước', kind: 'Huyện', city_id: '80'},
  # {id: , code: '807',name: 'Huyện Cần Giuộc', kind: 'Huyện', city_id: '80'},
  # {id: , code: '808',name: 'Huyện Châu Thành', kind: 'Huyện', city_id: '80'},
  # {id: , code: '815',name: 'Thành phố Mỹ Tho', kind: 'Thành phố', city_id: '82'},
  # {id: , code: '816',name: 'Thị xã Gò Công', kind: 'Thị xã', city_id: '82'},
  # {id: , code: '817',name: 'Thị xã Cai Lậy', kind: 'Huyện', city_id: '82'},
  # {id: , code: '818',name: 'Huyện Tân Phước', kind: 'Huyện', city_id: '82'},
  # {id: , code: '819',name: 'Huyện Cái Bè', kind: 'Huyện', city_id: '82'},
  # {id: , code: '820',name: 'Huyện Cai Lậy', kind: 'Thị xã', city_id: '82'},
  # {id: , code: '821',name: 'Huyện Châu Thành', kind: 'Huyện', city_id: '82'},
  # {id: , code: '822',name: 'Huyện Chợ Gạo', kind: 'Huyện', city_id: '82'},
  # {id: , code: '823',name: 'Huyện Gò Công Tây', kind: 'Huyện', city_id: '82'},
  # {id: , code: '824',name: 'Huyện Gò Công Đông', kind: 'Huyện', city_id: '82'},
  # {id: , code: '825',name: 'Huyện Tân Phú Đông', kind: 'Huyện', city_id: '82'},
  # {id: , code: '829',name: 'Thành phố Bến Tre', kind: 'Thành phố', city_id: '83'},
  # {id: , code: '831',name: 'Huyện Châu Thành', kind: 'Huyện', city_id: '83'},
  # {id: , code: '832',name: 'Huyện Chợ Lách', kind: 'Huyện', city_id: '83'},
  # {id: , code: '833',name: 'Huyện Mỏ Cày Nam', kind: 'Huyện', city_id: '83'},
  # {id: , code: '834',name: 'Huyện Giồng Trôm', kind: 'Huyện', city_id: '83'},
  # {id: , code: '835',name: 'Huyện Bình Đại', kind: 'Huyện', city_id: '83'},
  # {id: , code: '836',name: 'Huyện Ba Tri', kind: 'Huyện', city_id: '83'},
  # {id: , code: '837',name: 'Huyện Thạnh Phú', kind: 'Huyện', city_id: '83'},
  # {id: , code: '838',name: 'Huyện Mỏ Cày Bắc', kind: 'Huyện', city_id: '83'},
  # {id: , code: '842',name: 'Thành phố Trà Vinh', kind: 'Thành phố', city_id: '84'},
  # {id: , code: '844',name: 'Huyện Càng Long', kind: 'Huyện', city_id: '84'},
  # {id: , code: '845',name: 'Huyện Cầu Kè', kind: 'Huyện', city_id: '84'},
  # {id: , code: '846',name: 'Huyện Tiểu Cần', kind: 'Huyện', city_id: '84'},
  # {id: , code: '847',name: 'Huyện Châu Thành', kind: 'Huyện', city_id: '84'},
  # {id: , code: '848',name: 'Huyện Cầu Ngang', kind: 'Huyện', city_id: '84'},
  # {id: , code: '849',name: 'Huyện Trà Cú', kind: 'Huyện', city_id: '84'},
  # {id: , code: '850',name: 'Huyện Duyên Hải', kind: 'Huyện', city_id: '84'},
  # {id: , code: '851',name: 'Thị xã Duyên Hải', kind: 'Thị xã', city_id: '84'},
  # {id: , code: '855',name: 'Thành phố Vĩnh Long', kind: 'Thành phố', city_id: '86'},
  # {id: , code: '857',name: 'Huyện Long Hồ', kind: 'Huyện', city_id: '86'},
  # {id: , code: '858',name: 'Huyện Mang Thít', kind: 'Huyện', city_id: '86'},
  # {id: , code: '859',name: 'Huyện  Vũng Liêm', kind: 'Huyện', city_id: '86'},
  # {id: , code: '860',name: 'Huyện Tam Bình', kind: 'Huyện', city_id: '86'},
  # {id: , code: '861',name: 'Thị xã Bình Minh', kind: 'Thị xã', city_id: '86'},
  # {id: , code: '862',name: 'Huyện Trà Ôn', kind: 'Huyện', city_id: '86'},
  # {id: , code: '863',name: 'Huyện Bình Tân', kind: 'Huyện', city_id: '86'},
  # {id: , code: '866',name: 'Thành phố Cao Lãnh', kind: 'Thành phố', city_id: '87'},
  # {id: , code: '867',name: 'Thành phố Sa Đéc', kind: 'Thành phố', city_id: '87'},
  # {id: , code: '868',name: 'Thị xã Hồng Ngự', kind: 'Thị xã', city_id: '87'},
  # {id: , code: '869',name: 'Huyện Tân Hồng', kind: 'Huyện', city_id: '87'},
  # {id: , code: '870',name: 'Huyện Hồng Ngự', kind: 'Huyện', city_id: '87'},
  # {id: , code: '871',name: 'Huyện Tam Nông', kind: 'Huyện', city_id: '87'},
  # {id: , code: '872',name: 'Huyện Tháp Mười', kind: 'Huyện', city_id: '87'},
  # {id: , code: '873',name: 'Huyện Cao Lãnh', kind: 'Huyện', city_id: '87'},
  # {id: , code: '874',name: 'Huyện Thanh Bình', kind: 'Huyện', city_id: '87'},
  # {id: , code: '875',name: 'Huyện Lấp Vò', kind: 'Huyện', city_id: '87'},
  # {id: , code: '876',name: 'Huyện Lai Vung', kind: 'Huyện', city_id: '87'},
  # {id: , code: '877',name: 'Huyện Châu Thành', kind: 'Huyện', city_id: '87'},
  # {id: , code: '883',name: 'Thành phố Long Xuyên', kind: 'Thành phố', city_id: '89'},
  # {id: , code: '884',name: 'Thành phố Châu Đốc', kind: 'Thành phố', city_id: '89'},
  # {id: , code: '886',name: 'Huyện An Phú', kind: 'Huyện', city_id: '89'},
  # {id: , code: '887',name: 'Thị xã Tân Châu', kind: 'Thị xã', city_id: '89'},
  # {id: , code: '888',name: 'Huyện Phú Tân', kind: 'Huyện', city_id: '89'},
  # {id: , code: '889',name: 'Huyện Châu Phú', kind: 'Huyện', city_id: '89'},
  # {id: , code: '890',name: 'Huyện Tịnh Biên', kind: 'Huyện', city_id: '89'},
  # {id: , code: '891',name: 'Huyện Tri Tôn', kind: 'Huyện', city_id: '89'},
  # {id: , code: '892',name: 'Huyện Châu Thành', kind: 'Huyện', city_id: '89'},
  # {id: , code: '893',name: 'Huyện Chợ Mới', kind: 'Huyện', city_id: '89'},
  # {id: , code: '894',name: 'Huyện Thoại Sơn', kind: 'Huyện', city_id: '89'},
  # {id: , code: '899',name: 'Thành phố Rạch Giá', kind: 'Thành phố', city_id: '91'},
  # {id: , code: '900',name: 'Thị xã Hà Tiên', kind: 'Thị xã', city_id: '91'},
  # {id: , code: '902',name: 'Huyện Kiên Lương', kind: 'Huyện', city_id: '91'},
  # {id: , code: '903',name: 'Huyện Hòn Đất', kind: 'Huyện', city_id: '91'},
  # {id: , code: '904',name: 'Huyện Tân Hiệp', kind: 'Huyện', city_id: '91'},
  # {id: , code: '905',name: 'Huyện Châu Thành', kind: 'Huyện', city_id: '91'},
  # {id: , code: '906',name: 'Huyện Giồng Riềng', kind: 'Huyện', city_id: '91'},
  # {id: , code: '907',name: 'Huyện Gò Quao', kind: 'Huyện', city_id: '91'},
  # {id: , code: '908',name: 'Huyện An Biên', kind: 'Huyện', city_id: '91'},
  # {id: , code: '909',name: 'Huyện An Minh', kind: 'Huyện', city_id: '91'},
  # {id: , code: '910',name: 'Huyện Vĩnh Thuận', kind: 'Huyện', city_id: '91'},
  # {id: , code: '911',name: 'Huyện Phú Quốc', kind: 'Huyện', city_id: '91'},
  # {id: , code: '912',name: 'Huyện Kiên Hải', kind: 'Huyện', city_id: '91'},
  # {id: , code: '913',name: 'Huyện U Minh Thượng', kind: 'Huyện', city_id: '91'},
  # {id: , code: '914',name: 'Huyện Giang Thành', kind: 'Huyện', city_id: '91'},
  # {id: , code: '916',name: 'Quận Ninh Kiều', kind: 'Quận', city_id: '92'},
  # {id: , code: '917',name: 'Quận Ô Môn', kind: 'Quận', city_id: '92'},
  # {id: , code: '918',name: 'Quận Bình Thuỷ', kind: 'Quận', city_id: '92'},
  # {id: , code: '919',name: 'Quận Cái Răng', kind: 'Quận', city_id: '92'},
  # {id: , code: '923',name: 'Quận Thốt Nốt', kind: 'Quận', city_id: '92'},
  # {id: , code: '924',name: 'Huyện Vĩnh Thạnh', kind: 'Huyện', city_id: '92'},
  # {id: , code: '925',name: 'Huyện Cờ Đỏ', kind: 'Huyện', city_id: '92'},
  # {id: , code: '926',name: 'Huyện Phong Điền', kind: 'Huyện', city_id: '92'},
  # {id: , code: '927',name: 'Huyện Thới Lai', kind: 'Huyện', city_id: '92'},
  # {id: , code: '930',name: 'Thành phố Vị Thanh', kind: 'Thành phố', city_id: '93'},
  # {id: , code: '931',name: 'Thị xã Ngã Bảy', kind: 'Thị xã', city_id: '93'},
  # {id: , code: '932',name: 'Huyện Châu Thành A', kind: 'Huyện', city_id: '93'},
  # {id: , code: '933',name: 'Huyện Châu Thành', kind: 'Huyện', city_id: '93'},
  # {id: , code: '934',name: 'Huyện Phụng Hiệp', kind: 'Huyện', city_id: '93'},
  # {id: , code: '935',name: 'Huyện Vị Thuỷ', kind: 'Huyện', city_id: '93'},
  # {id: , code: '936',name: 'Huyện Long Mỹ', kind: 'Huyện', city_id: '93'},
  # {id: , code: '937',name: 'Thị xã Long Mỹ', kind: 'Thị xã', city_id: '93'},
  # {id: , code: '941',name: 'Thành phố Sóc Trăng', kind: 'Thành phố', city_id: '94'},
  # {id: , code: '942',name: 'Huyện Châu Thành', kind: 'Huyện', city_id: '94'},
  # {id: , code: '943',name: 'Huyện Kế Sách', kind: 'Huyện', city_id: '94'},
  # {id: , code: '944',name: 'Huyện Mỹ Tú', kind: 'Huyện', city_id: '94'},
  # {id: , code: '945',name: 'Huyện Cù Lao Dung', kind: 'Huyện', city_id: '94'},
  # {id: , code: '946',name: 'Huyện Long Phú', kind: 'Huyện', city_id: '94'},
  # {id: , code: '947',name: 'Huyện Mỹ Xuyên', kind: 'Huyện', city_id: '94'},
  # {id: , code: '948',name: 'Thị xã Ngã Năm', kind: 'Thị xã', city_id: '94'},
  # {id: , code: '949',name: 'Huyện Thạnh Trị', kind: 'Huyện', city_id: '94'},
  # {id: , code: '950',name: 'Thị xã Vĩnh Châu', kind: 'Thị xã', city_id: '94'},
  # {id: , code: '951',name: 'Huyện Trần Đề', kind: 'Huyện', city_id: '94'},
  # {id: , code: '954',name: 'Thành phố Bạc Liêu', kind: 'Thành phố', city_id: '95'},
  # {id: , code: '956',name: 'Huyện Hồng Dân', kind: 'Huyện', city_id: '95'},
  # {id: , code: '957',name: 'Huyện Phước Long', kind: 'Huyện', city_id: '95'},
  # {id: , code: '958',name: 'Huyện Vĩnh Lợi', kind: 'Huyện', city_id: '95'},
  # {id: , code: '959',name: 'Thị xã Giá Rai', kind: 'Thị xã', city_id: '95'},
  # {id: , code: '960',name: 'Huyện Đông Hải', kind: 'Huyện', city_id: '95'},
  # {id: , code: '961',name: 'Huyện Hoà Bình', kind: 'Huyện', city_id: '95'},
  # {id: , code: '964',name: 'Thành phố Cà Mau', kind: 'Thành phố', city_id: '96'},
  # {id: , code: '966',name: 'Huyện U Minh', kind: 'Huyện', city_id: '96'},
  # {id: , code: '967',name: 'Huyện Thới Bình', kind: 'Huyện', city_id: '96'},
  # {id: , code: '968',name: 'Huyện Trần Văn Thời', kind: 'Huyện', city_id: '96'},
  # {id: , code: '969',name: 'Huyện Cái Nước', kind: 'Huyện', city_id: '96'},
  # {id: , code: '970',name: 'Huyện Đầm Dơi', kind: 'Huyện', city_id: '96'},
  # {id: , code: '971',name: 'Huyện Năm Căn', kind: 'Huyện', city_id: '96'},
  # {id: , code: '972',name: 'Huyện Phú Tân', kind: 'Huyện', city_id: '96'},
  # {id: , code: '973',name: 'Huyện Ngọc Hiển', kind: 'Huyện', city_id: '96'},

].each do |attr|
  district = District.find_by(id: attr[:id])
  District.transaction do
    unless district
      district = District.new(attr)
      district.save
    else
      district.update_attributes attr
    end
  end
end
